/**
 * @file random.hpp
 * @brief A lightweight, modern C++23 wrapper for the <random> library.
 */

#pragma once

#include <algorithm>
#include <concepts>
#include <iterator>
#include <random>
#include <ranges>
#include <source_location>
#include <type_traits>

/**
 * @brief Core namespace for the rng library.
 */
namespace rng
{
/**
 * @cond INTERNAL
 * Internal implementation details. Not part of the public API.
 */
namespace _detail
{
#if defined(__cpp_exceptions) || defined(__EXCEPTIONS) || defined(_CPPUNWIND)
#define RNG_EXCEPTIONS_ENABLED 1
#else
#define RNG_EXCEPTIONS_ENABLED 0
#endif
inline void expect(bool condition, const char *message,
                   const std::source_location loc = std::source_location::current())
{
    if (condition)
        return; // All good, do nothing

#if RNG_EXCEPTIONS_ENABLED
    throw std::invalid_argument(std::string("RNG Error at ") + loc.file_name() + ":" +
                                std::to_string(loc.line()) + " - " + message);
#else
#include <print>
    std::println(stderr, "Fatal RNG Error at {}: {} - {}", loc.file_name(), loc.line(),
                 message);
    std::abort();
#endif
}
} // namespace _detail
/** @endcond */

/**
 * @brief Concept defining types that are either integral or floating-point.
 * @tparam T The type to check.
 */
template <typename T>
concept Arithmetic = std::integral<T> || std::floating_point<T>;

/**
 * @brief Concept defining a range that can be iterated forward and has a known size.
 * @tparam R The type to check.
 */
template <typename R>
concept SizedForwardRange =
    std::ranges::forward_range<R> && std::ranges::sized_range<R>;

/**
 * @brief Concept defining a Uniform Random Bit Generator (URBG).
 * @tparam T The type to check.
 */
template <typename T>
concept URBG = std::uniform_random_bit_generator<T>;

/**
 * @brief Helper struct to deduce the correct uniform distribution based on type.
 * @tparam Tp An arithmetic type (integral or floating-point).
 */
template <typename Tp>
    requires std::is_arithmetic<Tp>::value
struct UniformImpl
{
    using uniform_dist = std::conditional_t<std::is_floating_point_v<Tp>,
                                            std::uniform_real_distribution<Tp>,
                                            std::uniform_int_distribution<Tp>>;
};

/**
 * @brief Alias for the appropriate std::uniform_*_distribution type.
 * @tparam Tp The arithmetic type.
 */
template <typename Tp>
using uniform_dist = typename UniformImpl<Tp>::uniform_dist;

/**
 * @brief A robust wrapper around a Uniform Random Bit Generator (defaults to mt19937).
 * * Automatically initializes and warms up the underlying engine using std::seed_seq
 * to avoid common 32-bit seeding bottlenecks.
 * * @tparam Engine The underlying random engine (e.g., std::mt19937).
 */
template <typename Engine = std::mt19937>
    requires URBG<Engine>
class BitGen
{
public:
    using result_type = typename Engine::result_type;

    /** @brief Returns the minimum possible value generated by the engine. */
    static constexpr result_type min()
    {
        return Engine::min();
    }

    /** @brief Returns the maximum possible value generated by the engine. */
    static constexpr result_type max()
    {
        return Engine::max();
    }

    /**
     * @brief Default constructor. Seeds the engine securely using OS entropy.
     */
    BitGen()
        : _rnd_engine{}
    {
        std::random_device rd{};
        std::array<unsigned int, 8> seed_data;
        std::generate(seed_data.begin(), seed_data.end(), std::ref(rd));
        std::seed_seq seq(seed_data.begin(), seed_data.end());
        _rnd_engine.seed(seq);
    }

    /**
     * @brief Explicitly seeds the engine with a specific value.
     * @param seed The deterministic seed value.
     */
    explicit BitGen(result_type seed)
        : _rnd_engine{seed}
    {
    }

    /**
     * @brief Reseeds the engine.
     * @param s The new seed value.
     */
    void seed(result_type s)
    {
        _rnd_engine.seed(s);
    }

    /**
     * @brief Generates the next random number in the sequence.
     * @return A random value of result_type.
     */
    result_type operator()()
    {
        return _rnd_engine();
    }

    /**
     * @brief Advances the engine's state by z steps.
     * @param z The number of steps to discard.
     */
    void discard(unsigned long long z)
    {
        _rnd_engine.discard(z);
    }

private:
    Engine _rnd_engine;
};

/** * @brief A thread-local, default-seeded instance of BitGen used across the library.
 */
inline thread_local BitGen default_engine{};

/**
 * @brief Generates a random number uniformly distributed between [a, b].
 * * @tparam Tp The type of the lower bound.
 * @tparam Up The type of the upper bound.
 * @tparam Engine The type of the random engine.
 * @param a The lower bound (inclusive).
 * @param b The upper bound (inclusive).
 * @param bitgen The random engine to use (defaults to rng::default_engine).
 * @return A random value of the common type between Tp and Up.
 */
template <Arithmetic Tp, Arithmetic Up, URBG Engine = BitGen<>>
inline constexpr std::common_type_t<Tp, Up> uniform(Tp a, Up b,
                                                    Engine &bitgen = default_engine)
{
    uniform_dist<std::common_type_t<Tp, Up>> dist(a, b);
    return dist(bitgen);
}

/**
 * @brief Returns a randomly selected element from a non-empty range.
 * * @tparam Rg A forward range with a known size.
 * @tparam Engine The type of the random engine.
 * @param range The collection to pick an element from.
 * @param bitgen The random engine to use (defaults to rng::default_engine).
 * @return A reference or copy of the randomly selected element.
 * @throws std::invalid_argument (or aborts) if the range is empty.
 */
template <SizedForwardRange Rg, URBG Engine = BitGen<>>
constexpr inline decltype(auto) choice(Rg &&range, Engine &bitgen = default_engine)
{

    _detail::expect(!std::ranges::empty(range), "Range is empty!");
    auto len = std::ranges::size(range);
    auto const ind = uniform(0, len - 1, bitgen);
    return *std::ranges::next(std::ranges::begin(range), ind);
}

/**
 * @brief Returns an element from a range, biased by a pre-computed discrete
 * distribution.
 * * @tparam Rg A forward range with a known size.
 * @tparam IndexType The integer type returned by the discrete distribution.
 * @tparam Engine The type of the random engine.
 * @param range The collection to pick an element from.
 * @param weights A pre-configured std::discrete_distribution.
 * @param urbg The random engine to use (defaults to rng::default_engine).
 * @return A reference or copy of the randomly selected element.
 * @throws std::invalid_argument (or aborts) if sizes mismatch or range is empty.
 */
template <SizedForwardRange Rg, std::integral IndexType, URBG Engine = BitGen<>>
constexpr inline decltype(auto) choices(Rg &&range,
                                        std::discrete_distribution<IndexType> &weights,
                                        Engine &urbg = default_engine)
{
    auto const _wz = weights.probabilities().size();
    _detail::expect(!std::ranges::empty(range), "Range is empty!");
    _detail::expect(std::ranges::size(range) == _wz, "Size mismatch!");
    auto const ind = weights(urbg);
    return *std::ranges::next(std::ranges::begin(range), ind);
}

/**
 * @brief Returns an element from a range, biased by an inline list of weights.
 * * @warning Do not use this overload in a tight loop, as it constructs the
 * distribution on every call. Use the std::discrete_distribution overload instead.
 * * @tparam Rg A forward range with a known size.
 * @tparam Tp The arithmetic type of the weights.
 * @tparam Engine The type of the random engine.
 * @param range The collection to pick an element from.
 * @param weights An initializer_list of weights (e.g., {10, 50, 40}).
 * @param urbg The random engine to use (defaults to rng::default_engine).
 * @return A reference or copy of the randomly selected element.
 */
template <SizedForwardRange Rg, Arithmetic Tp, URBG Engine = BitGen<>>
constexpr inline decltype(auto) choices(Rg &&range, std::initializer_list<Tp> weights,
                                        Engine &urbg = default_engine)
{
    std::discrete_distribution<std::size_t> dist(weights.begin(), weights.end());
    return choices(std::forward<Rg>(range), dist, urbg);
}
} // namespace rng
